language: csharp
script:
- rake build --trace
- ls -lR
deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file: output/*.nupkg
  api_key:
    secure: fPXT/cWTnUTfOS/Gz3Tr48G3KW7H6F0ADk7n0NH65HhLV7579gUbdnFeQ8aiiCF/dCSQalUtv5Gl2qYSfvdOt7DN4C5RvsozRw6lFWh0ivDquSf4sHQRIHKHAfCiTIL5H6q+azkiRf6NdJATfQxa48Tsp2ia4PyfO1scTSB+Yyva8Q7q0DKE7xAzfplh3L9Xa9/jauCSfuO587oRlli0L7RIjzko7/L7HF8hxYDj+m4jDmNYyUWJvNLAdvbJV1f7jsQVaglHHsDlOC4j8tEIZO9q5uBsGoBqKuWFOdkxOBFOCWxnXgcLza7I4gZ/4F99qSZ5t/SsM5fuTPcwJ9yrMyZ3Qe+eSn6ukE0LN7iaoE4bAic4obJOoWhOmzv1UAveD4nV6EhAJoaAxN9N2DugyKheVmvc29OaK7/R+lCm5pJnTSMcwIkAd0CWg4/L4WFELrMBeSnjiVWx+lrZocxu0gNQMLjN9k/oyvXpiPM9ujB4vFztGzh1Kv0UZXebLPR9NbszGrLFSdRmLRFHRmp57+8Iu6XCKnCp9ywYzcACsOgNnsg/Z74otiVa99xeapwJmCppmLTe0QzJKn0Lt5TdVICQ3uJVwM4usCfuTPj/CrW5pBQdHygRuJlDwoUN2eYxFRtblAkpsEhVVu3SbQnwER4993cdIEj+8iTtf0ucK4w=
  on:
    tags: false
    all_branches: true
branches:
  only:
  - master
  - /^release.*/
env:
  global:
  - secure: bdSa09LXDa0hacJNy/OyZjcZ70vYyd3a9OhJvrvhS3v85JEI78rHo2MC9njBHQfKYWa7WH2Hx/TLM+F5YthqQgKbpSrWwVrezwO/QMjpi5Oy0vhvo6F3nCSomdyJE48KGNwU+uUGIHVVcgycj2i9BQV4asHEwLMoUC/HnRvtgWV4Kmc8m/EXfKBMFMzIT+AuEYY0NGYXmRsnSq8JI+/2ebUxqGxNQemuaiQju5aZSaonqguAsFGoIHrBiQ77ireXMGq0927tS9TEUkBlSC5qG7Rc8flu7FWbxkWNhsKdrM7KTpcjrwzBsYnf9xUHUcc2pI8F1Y9ZhTwlT85T7HeznEkw+dZBPTB1qa07xYf80WBrL7qcEOOWAte6IrW1qEbY3HdU0WGffAXjmhVsi4+EcpbZn4t0S7RGJsFqnfom/7rG3Y8Ek91rnlokTblqCu2xV2zZHDicuLuR1Nc5QwueyJ7DaQVrW8lrECsiCGQHUli3hWeeHHgESuaJp/7TN6PQkAfB9ZJyT4wLHb1KE1GJzhNKqtvYGTbKJ+Q0uI/drx2FnCZ9NITZEf81woOGWyKKjsACfGDQy15Xo3hYoRx5kBlMHSsxru5bp/koKBnKXvWhWGMnj+wUecTtZx0mGZiICVx629mUB8XmG6jYr3gQKFafnPtULlvnXPN2GkQCz38=
